/**
 * @module types
 * @description Core type definitions for the command system of Tab Manager Pro.
 * Defines the intent types recognized by the natural language parser, the structure
 * of parsed intents, command execution results, and chat history entries.
 */

/**
 * @description All supported intent types that can be recognized from user input.
 * Each value corresponds to a specific tab management action or a generic chat fallback.
 *
 * - `close_duplicates` - Close tabs with duplicate URLs
 * - `group_tabs` - Automatically group tabs by domain or AI classification
 * - `close_tab` - Close a specific tab matching a query
 * - `save_session` - Save the current set of tabs as a named session
 * - `restore_session` - Restore a previously saved session
 * - `create_workspace` - Create a new workspace from the current tabs
 * - `open_workspace` - Open an existing workspace
 * - `sort_tabs` - Sort tabs alphabetically by domain
 * - `close_inactive` - Close all non-active, non-pinned tabs
 * - `search_tabs` - Search for tabs matching a query
 * - `chat` - Generic chat message that does not map to a command
 */
export type IntentType =
  | 'close_duplicates'
  | 'group_tabs'
  | 'close_tab'
  | 'save_session'
  | 'restore_session'
  | 'create_workspace'
  | 'open_workspace'
  | 'sort_tabs'
  | 'close_inactive'
  | 'search_tabs'
  | 'chat';

/**
 * @description Represents a parsed user intent extracted from natural language input.
 * Produced by the parser and consumed by the executor.
 *
 * @example
 * ```ts
 * const intent: ParsedIntent = {
 *   type: 'close_tab',
 *   params: { query: 'YouTube' },
 *   originalText: 'close the tab YouTube',
 * };
 * ```
 */
export interface ParsedIntent {
  /** @description The recognized intent type. */
  type: IntentType;
  /** @description Extracted parameters relevant to the intent (e.g., tab query, session name). */
  params: Record<string, string | undefined>;
  /** @description The original user input text that was parsed. */
  originalText: string;
}

/**
 * @description The result of executing a command, indicating success or failure
 * along with a human-readable message and optional payload data.
 *
 * @example
 * ```ts
 * const result: CommandResult = {
 *   success: true,
 *   message: '3 duplicate(s) closed.',
 * };
 * ```
 */
export interface CommandResult {
  /** @description Whether the command executed successfully. */
  success: boolean;
  /** @description A human-readable message describing the outcome. */
  message: string;
  /** @description Optional additional data returned by the command (e.g., list of matched tabs). */
  data?: any;
}

/**
 * @description A single entry in the chat history, capturing both user and assistant
 * messages along with optional intent and command result metadata.
 *
 * @example
 * ```ts
 * const entry: ChatHistoryEntry = {
 *   id: 'lxyz1234ab',
 *   timestamp: 1711843200000,
 *   userMessage: 'close duplicates',
 *   assistantMessage: '3 duplicate(s) closed.',
 *   intent: 'close_duplicates',
 *   commandResult: { success: true, message: '3 duplicate(s) closed.' },
 * };
 * ```
 */
export interface ChatHistoryEntry {
  /** @description Unique identifier for the history entry. */
  id: string;
  /** @description Unix timestamp (in milliseconds) when the entry was created. */
  timestamp: number;
  /** @description The message sent by the user. */
  userMessage: string;
  /** @description The response generated by the assistant. */
  assistantMessage: string;
  /** @description The intent type that was detected from the user message, if any. */
  intent?: IntentType;
  /** @description The result of the executed command, if a command was triggered. */
  commandResult?: CommandResult;
}
